# Generated by Django 5.2.10 on 2026-02-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('college_name', models.CharField(max_length=200)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('message', models.TextField()),
                ('sentiment', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
